/*
 * Copyright(C) Letty Co.Ltd. 2011 All Rights Reserved.
 *
 * system name	: 
 * class name	: RowDto_Test.cls
 * remarks		: 
 * version		: 1.0.0
 * create		: [1.0.0] 2011/07/29 Li Lin
 * update
 */
@isTest
private class RowDto_Test
{

	static testMethod void myUnitTest()
    {

		//---------------------------------
		//	テスト対象クラスを生成する
		//---------------------------------
		RowDto rowDto = new RowDto();

	}
}